# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_anyone_register', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'configurationes',
                'verbose_name': 'configuration',
            },
        ),
    ]
